baseURL = "https://docs.talos-systems.com/"
languageCode = "en-us"
title = "Talos"
theme = "hugo-theme-talos"
sectionPagesMenu = "main"

[outputs]
  home = ["HTML", "RSS", "JSON"]

[params]
    Copyright = "Released under Mozilla Public License 2.0"
    GitHubLink = "https://github.com/talos-systems/talos"
    DockerHubLink = "https://hub.docker.com/u/talos-systems"
